# Generated by Django 2.2 on 2020-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201004_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
