# Generated by Django 2.2 on 2020-10-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_user_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user_votes',
        ),
    ]
