# Generated by Django 2.2 on 2020-10-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_choice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
