# Generated by Django 2.2 on 2020-10-07 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_poll_voted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['field']},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='voted',
        ),
        migrations.AlterField(
            model_name='choice',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
