# Generated by Django 2.2 on 2020-10-07 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_userchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoices',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
