# Generated by Django 2.2 on 2020-10-07 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20201007_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userchoices',
            options={'verbose_name_plural': 'user_choices'},
        ),
        migrations.AlterField(
            model_name='userchoices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='choices', to=settings.AUTH_USER_MODEL),
        ),
    ]
