# Generated by Django 2.2 on 2020-10-07 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0014_auto_20201007_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='users',
            field=models.ManyToManyField(related_name='polls_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
