# Generated by Django 2.2 on 2020-10-07 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20201007_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
