# Generated by Django 2.2 on 2020-10-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_uservotes_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservotes',
            name='voted',
        ),
    ]
