# Generated by Django 2.2 on 2020-10-08 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20201008_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservotes',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_voted', to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='uservotes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
