# Generated by Django 2.2 on 2020-10-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20201008_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote_limit',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
