# Generated by Django 2.2 on 2020-10-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_poll_vote_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservotes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls_voted', to=settings.AUTH_USER_MODEL),
        ),
    ]
