# Generated by Django 2.2 on 2020-10-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20201010_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservotes',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
