# Generated by Django 2.2 on 2020-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_auto_20201010_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='vote_limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
