# Generated by Django 2.2 on 2020-10-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0031_auto_20201010_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservotes',
            name='user_ip',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
